### ISSUE TITLE
The color choice makes it so i cant see the address with EAL installed

### ISSUE THREAD

**Issue by GriffGreen** [dappnode/DAppNode_website#1]
![screen shot 2018-06-18 at 2 09 15 pm](https://user-images.githubusercontent.com/14945613/41562417-60df1b64-7301-11e8-9af8-6e9532e5bc0f.png)
This is because I have been to that link and this color is the same color as a clicked hyper link... 

Either way.. i am literally trying to donate and can't see the address... i would say this is worth changing the background color behind the QR code... if not the whole wensite... Might i suggest a forrest green (insert DrEvilFingertoLip meme here)

**Comment by geleeroyale** [comment]
Thanks! Same issue was brought forward by @krrisis as well. Fixed in [this commit] (https://github.com/dappnode/DAppNode_website/commit/e233c4b99512ccc0f2f19c9839d748c607feddc5)
