### ISSUE TITLE
Redesign website.

### ISSUE THREAD

**Issue by Anish-Agnihotri** [dappnode/DAppNode_website#3]
Hey everyone!

This is the beginning of a thread based on the brief conversation that happened on the Riot server. I'm looking to help redesign the DAppNode website to give it a modern uplift. I had originally posted a cleaner demo of the current website with optimized file size, proper responsive CSS, and small design changes (here: https://anish-agnihotri.github.io/dappnode-redesign/), but @dapplion spoke about straying from the original design, which would obviously be a better idea.

**Current Issues:**
1. Website doesn't have a cohesive theme with the rest of the DAppNode applications.
2. It looks somewhat outdated, with not 100% responsive CSS, and various reused elements over the page.
3. It is pulling 36 external requests, with a 932KB page size, resulting in a 38% Lighthouse, 83% Pagespeed, and 85% YSlow score.
4. It is only one page, which is a landing page.

**Design Ideas:**
1. I'd like to expand the website to have landing, documentation, community, and more. A lot of my inspiration comes from websites like https://makerdao.com/ (especially the community call-to-action) and https://bloom.co (especially the developer documentation). 

Examples of what I mean:
![daocommunity](https://user-images.githubusercontent.com/4398624/50575820-3762e780-0dd3-11e9-950d-5d1ba695ce9c.JPG)
![bloomdocs](https://user-images.githubusercontent.com/4398624/50575821-392cab00-0dd3-11e9-96a5-35595cd4185b.JPG)

**Development Ideas:**
1. I can stick to React, switch to Vue/Mithril, or do completely static assets + static file host if you'd like.

I'm open for thoughts, ideas, etc. Feel free to comment below and post anything you've got in mind and I'd love to have a chat!

Also, just an FYI, the SSL certificate on https://dappnode.io expired four days ago. It should be auto-renewed though hopefully 🤞 .

**Comment by Anish-Agnihotri** [comment]
Working on an about page at the moment. Heres a sneak preview: 
![preview](https://user-images.githubusercontent.com/4398624/50577694-ab18ea80-0dfb-11e9-9973-755b1bb86b4d.JPG)

I'll keep dropping things as I go, please feel free to comment on what you like, what you don't, what you need, things to change, etc.

**Comment by Anish-Agnihotri** [comment]
Migrated the above page to the main page actually, and added quite a bit of stuff while I was at it: 

Here is a live preview: https://anish-agnihotri.github.io/dappnode-redesign/ 

Still super rough ofc. The menu is not even close to responsive, and other stuff still needs to be done, but the main page is slowly coming together.

Screenshot of live preview at current stage:
![screencapture-anish-agnihotri-github-io-dappnode-redesign-2019-01-02-16_32_00](https://user-images.githubusercontent.com/4398624/50613590-fd194900-0eab-11e9-98d6-b848f1227ff9.png)

As always, feel free to comment and let's discuss where to take this.

**Comment by dapplion** [comment]
@Anish-Agnihotri Huge thanks to you for leading this massively necessary initiative. I agree with the https://makerdao.com/ and https://bloom.co  as references, the last version you posted of https://anish-agnihotri.github.io/dappnode-redesign/ is looking very good! I would request to stick to react as that what the team knows, so in case we have to push update. A part from that you can modularize ditch components or whatever is necessary to fulfill your goals, specially to address your point number 3

> It is pulling 36 external requests, with a 932KB page size, resulting in a 38% Lighthouse, 83% Pagespeed, and 85% YSlow score.

I outlined this hackmd with the key concepts for the new version of the dappnode.io site. You are already embracing them but I'll share just in case https://hackmd.io/uJmhp9Z9QyitN9QGzwSjqQ?both.
- Due to the quality and relevance of our promo video, dappnode.io has to be **video driven**.
- Short to-the-point information. Include one headline and one explanatory sentence at most.
- Avoid long text explanations, that is taken care by the video.
- Include one single and clear call for action button.
- No long scroll-down page, restrict total content to what state above (video + headline + call-for-action), links to github/riot, supported by section, and not much extra content.

Do you think we should reduce the number of benefits? Right now there are 18, and we can figure out with the team which ones are really important.

**Comment by Anish-Agnihotri** [comment]
Thanks for the fantastic overview and summary! I’m glad to be able to help in anyway, and I love web development, so it all ties in! The hackmd you supplied is perfect for defining what you’re looking for in the website. 

First off, I’ll migrate the website to React. Makes complete sense, and after I had started some of the sections of the website, I realized it was inevitable, since routing menu pages manually, especially for when I add in the documentation section with its own set of pages would be a nightmare. That and the fact that to keep it DRY, it would make sense to define the components once and then route the data through, rather than the manual rendering that is currently being done by copy/pasting HTML content. 

Next, the hackmd clears up a lot of my confusions, haha. I was going through the Medium blog today and noticed the incredible
Promo video, and was thinking to myself why it wasn’t the showcase. Focusing on video-first, with a bold cta, and minimal text sounds like the best way to go. On that note, I also noticed that some of the benefits were redundant. I went ahead and cut a lot of them down to one-liners, and removed some of the longer ones, but it would make most sense if the team could go over those and decide on maybe the 5-6 absolute most important ones to showcase, and I can migrate those away from the landing to possibly a secondary page like about. I think they would probably be the technology focused ones, so things like VPN, browse eth domains, etc., but that is certainly something that we can talk about.

Altogether, I’m looking forward to helping out and getting a fresh look out the door with the new year! I’ll keep dropping updates as I go here and maybe more infrequent ones on the Riot, but please do feel free to interject whenever you’d like. In addition, since Github pages doesn’t compile React, I’ll setup a heroku applet quickly tomorrow so that there’s always a way to access the dev version of the repository live (without the hassle of setting it all up, haha). 

And, forewarning: I sometimes run astray with ideas upon ideas, and feedback is always appreciated to stay aligned to the end goal of a simple revised site :). So, do let me know if you think something should be changed, added, etc. And I’d be more than happy to have a chat!

**Comment by dapplion** [comment]
So happy to see your enthusiasm <3

I recommend you to check out create-react-app if you haven't https://reactjs.org/docs/create-a-new-react-app.html#create-react-app, it comes with all the webpack / bundling / build setup. Then you use this awesome tool that totally automates the gh-pages deployment of a create-react-app with a 3 lines of code https://github.com/gitname/react-gh-pages#tutorial. 

I'm glad the hackmd helped you to clear things up. I would for now suggested on doing one single page with all the content in the main (and only) route. The top navigation bar can reference locations within the same page triggering an autoscroll.

Please keep me updated, I can help on direction / design or pure code questions you may have!

**Comment by Anish-Agnihotri** [comment]
Oh! That tool is fantastic, thanks for linking! I'll take a look at it and migrate over to React, deploying to Github pages for sure.

And, for sure. I'll begin with just the single one page landing with the navbar links smooth-scrolling to anchor points on the page. 

I'll keep you updated and will comment if I need anything or for feedback!

**Comment by Anish-Agnihotri** [comment]
Just dropping an update. Had a busy last two days, but setup the React app with publishing to `gh-pages` today. I'm aiming to have everything completed and ready for a review within the next week at most.

**Comment by Anish-Agnihotri** [comment]
```
IMHO I suggest a prominent link to the readthedocs documentation in the dappnode.io page and differenciate it from the current wiki documentation? it is a bit confusing which one is the relevant one. If there is a linnk there I didnt find it . Maybe a top menu with links to github, readthedocs etc could be useful ...
```

Noticed some comments on the Riot and just wanted to know thoughts on this. I'm working on a large video focused CTA at the top (I'll push within the next day), and am wondering if you'd like me to add menu links at the top to the github, etc?

**Comment by dapplion** [comment]
@Anish-Agnihotri I can confirm that we will assign a bounty for your contribution on this! Can you update me on your progress? Where can I see the latest version? Thank you!

**Comment by Anish-Agnihotri** [comment]
Hey @dapplion!

Sorry for going MIA there. Got tied up in some stuff over the past week in-person and was unable to commit as much.

A bounty sounds amazing, but in all honestly, is truly not needed. I'd be as happy if the funds were used elsewhere for platform development. I'm glad to help in any way :)!

I've just road-mapped a timeline for myself right now. I'm pushing to have a MVP for you before end-of-day Tomorrow, or early Saturday, if that sounds good. I'll drop a live link here so you can see progress as I go tomorrow. That way, after you and the team take a look and provide feedback, I can aim for final completion before the end of the week (24th). 

Let me know how that sounds, and feel free to drop any additional info/comments/concerns.

**Comment by Anish-Agnihotri** [comment]
Hey folks, apologies for dropping out here. 

I'm in the middle of exam season atm (till Feb. 2) so its been a bit difficult to stay on top of things on Github. Here is my progress so far and an optimistic outlook into where I'm going:

**Progress**
At the moment, I'm simply beginning by migrating the HTML/CSS/JS I had previously made over to Gatsby (static site generation on React). I've used super stripped-down React since our requirements our close to none when it comes to things like dynamic content generation. [Here](https://serene-jang-4fa90e.netlify.com/) is a quick preview as I work.

I've been following the HackMD more closely and am solving some issues (things like making the website more video-centric). Other than this, I'm first converting the existing website I had built into React (keeping it a one-pager though to stick to the HackMD). Once this is completed, I'll begin to remove things that are not needed, and add things that are, followed by a final round of optimizations, lazy loads, compression, etc.

**Timeline/outlook**
I think I've got around 10-12 hours worth of work left on finishing this up and getting it launch ready, although, I won't be able to put in those hours till near the end of this month. I'll drop a message within the next week (think Friday this upcoming week) with my to-do's, since I should be nearly finished any commitments I have by then.

Other than that, open to feedback as always, and looking forward to knocking this out!

**Comment by Shelpin** [comment]
Wow!! @Anish-Agnihotri thank you so much for your support... it is awesome that people like you is part of DappNode´s community... we really appreciate your efforts to contribute to this venture. I really like what i have seen in the link you sent... will create a riot room with @eduadiez and @dapplion to have a more fluid communication to finish an amazing new site with your so valuable help... Cheers!
